# .github/workflows/ci.yml
name: CI

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - '**'

jobs:
  lint:
    name: Lint (flake8 + mypy)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install flake8 mypy

      - name: Run flake8
        run: flake8 app

      - name: Run mypy
        run: mypy app

  test:
    name: Test (pytest)
    runs-on: ubuntu-latest
    needs: lint
    # services:
      # SQLite はファイルベースなので不要ですが、PostgreSQL/MySQL を使う場合は設定
      # postgres:
      #   image: postgres:15
      #   ports: ['5432:5432']
      #   env:
      #     POSTGRES_USER: user
      #     POSTGRES_PASSWORD: pass
      #     POSTGRES_DB: testdb
      #   options: >-
      #     --health-cmd="pg_isready -U user" 
      #     --health-interval=10s 
      #     --health-timeout=5s 
      #     --health-retries=5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q

  docker-build:
    name: Build & Push Docker image
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_USERNAME }}/gpu-reservation-backend:latest
            ${{ secrets.DOCKER_USERNAME }}/gpu-reservation-backend:${{ github.sha }}

